### ISSUE TITLE
Cannot write file - System.ObjectDisposedException cannot access a closed file

### ISSUE THREAD

**Issue by cfelstead** [siisltd/Curiosity.SPSS#6]
Hi.

I use your library for reading SPSS files and trimming existing libraries. This works well. However, I have just tried to create one for scratch and I get an error "System.ObjectDisposedException cannot access a closed file".

To recreate, simply create a .net 7 console application and copy and paste the code from your GitHub homepage. The SPSS file is created correctly but the application crashes on closure.

At the moment, I am mitigating this by using someone elses fork but thought you should know.

Chris.

**Comment by Markeli** [comment]
Hi, Chris!

Sorry for a long reply and thanks for a bug report.

Unfortunately, I can't reproduce the bug. I've created a simple .NET 7 app as you write, copied and and pasted the code of reading SPSS file, and all works fine without exception.

Please, can you give us more details to help reproduce the bug? For example, dotnet SDK version, `Curisoity.SPPS` package version. Test SPSS file is also appreciated.

**Comment by Markeli** [comment]
I found mistake in readme example - `SpssReader` instance wasn't disposed. I've placed it in using. Maybe, this fix can help you. But in my environment and with my test files all works fine without this fix.
